### ISSUE TITLE
spca: objective improvement is actually the prior iteration improvement

### ISSUE THREAD

**Issue by tyner** [erichson/spca#1]
In the code, the updated value of the objective is appended to 'obj', so then at that point 'obj' has length noi + 1, so the improvement being calculated is actually the prior iteration's improvement, not the current iteration's improvement:
```r      
      # compute objective function
      obj <- c(obj, 0.5 * sum(R**2) + alpha * sum(abs(B)) + 0.5 * beta * sum(B**2))

      # Break if obj is not improving anymore
      if(noi > 1){
        improvement <- (obj[noi-1] - obj[noi]) / obj[noi]
      }
```
this seems like a bug to me...

**Comment by erichson** [comment]
@tyner this is a great catch, it seems I was thinking in python. Feel free to push the fix, otherwise, I can fix it myself, of course. Thanks a lot!

**Comment by tyner** [comment]
If I start editing this, I'll be strongly tempted to make other enhancements, for example initializing the objective to come from svd_init (instead of initializing to Inf); would you be interested in that?

**Comment by erichson** [comment]
@tyner that would be great, indeed. Enhancements are always welcome!

**Comment by mhriemers** [comment]
@tyner That is not true. `obj` is initialized as an empty vector and `noi` is initialized as `1`. In the first iteration, after computing the objective function, `noi <- 1` and `obj` is a vector of size 1. This is true for all subsequent iterations, the size of `obj` is always equal to `noi` at the following line

```r
# Break if obj is not improving anymore
if(noi > 1){
    improvement <- (obj[noi-1] - obj[noi]) / obj[noi]
}
```

**Comment by tyner** [comment]
thanks @ipsq, you are quite right. Sorry for the false alarm.
