### ISSUE TITLE
DESCRIPTION file name error

### ISSUE THREAD

**Issue by daifengqi** [erichson/spca#4]
Hi @erichson , we cannot install development version now because the package name is not correct. I guess that either change the statement to `devtools::install_github(erichson/sparsepca)' or change the DESCRIPTION file's first row to [Package: spca] can solve the problem. Many thanks~

**Comment by erichson** [comment]
@daifengqi I am not sure about that. I just tried to execute the following command: 
`devtools::install_github(erichson/spca)`
and it worked fine for me. What is the error message that you got? And does
`install.packages("sparsepca")`
work for you?

Best,
Ben

**Comment by daifengqi** [comment]
Hi Ben, `install.packages("sparsepca")` always works. I just try `devtools::install_github(erichson/spca)` and it works.
Last time some of my classmate tried to install the development version and it returned error like this:
`Failed to install 'unknown package' from Github: Does not appear to be an R package(no DESCRIPTION)`
[error message](https://i.loli.net/2020/07/26/J5yTgW8U4PFfRpA.png)

It may be caused by some strange problems...

Regards,
Cesc

**Comment by erichson** [comment]
@daifengqi, I am happy to hear that it works now. :)

Best,
Ben
