### ISSUE TITLE
Explained variance

### ISSUE THREAD

**Issue by DominiqueMakowski** [erichson/spca#5]
Just a quick question, I've seen in several places when computing the variance explained that the variance is divided by the sum of variances (so that the total is 1), whereas here the denominator is computed differently (`sum( apply( Re(X) , 2, stats::var ) )`):

https://github.com/erichson/spca/blob/fa896289a68801a4798f53948ff6c2b8f7c54e1c/R/spca.R#L291

The two methods give slightly different results:

``` r
x <- sparsepca::spca(mtcars[1:7], verbose=FALSE)

# Cumulative variance ("traditional" method)
var <- x$sdev**2
cumsum(var / sum(var))
#> [1] 0.9273919 0.9995292 0.9999185 0.9999790 0.9999934 0.9999970 1.0000000

# Current method
cumsum(x$sdev**2 / x$var)
#> [1] 0.9269049 0.9990043 0.9993933 0.9994539 0.9994683 0.9994719 0.9994748
```

<sup>Created on 2022-09-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I was wondering which one was correct

**Comment by erichson** [comment]
Hi @DominiqueMakowski, thanks for looking at the code. The traditional method is correct, but it requires that you actually compute all eigenvalues (which is expensive). My SPCA implementation can take advantage of randomized methods to approximate just the top k eigenvectors / values of interest (which is much faster), but the price is that I don't have information about the remaining eigenvalues. Thus, I use (sum( apply( Re(X) , 2, stats::var ) )) as an approximation for sum of variances. The result is close, but not exact. In practice it should not matter too much. 

Maybe there should be an option in the code for using the traditional method in case that computational time doesn't matter.

Best,
Ben

**Comment by DominiqueMakowski** [comment]
Thanks for the clarification :)
