### ISSUE TITLE
predict() method for spca

### ISSUE THREAD

**Issue by DominiqueMakowski** [erichson/spca#7]
Hi! I wanted to know if it was possible (and if so, whether it is hard) to implement a predict method to extrapolate the components' score to new data.

Example with base R PCA:

``` r
pca <- princomp(iris[1:50, 1:4])  # Fit the PCA on the first 50 observations

# Precdict scores on all the data (150 rows)
predict(pca, newdata=iris[, 1:4]) |> 
  head()
#>          Comp.1      Comp.2      Comp.3       Comp.4
#> [1,]  0.1068424 -0.02489398  0.08216974  0.034541755
#> [2,] -0.3940472  0.16586593  0.13148092  0.017551195
#> [3,] -0.3906877 -0.12685112  0.07181182 -0.009744303
#> [4,] -0.5117016 -0.02656106 -0.11121361  0.032673214
#> [5,]  0.1133493 -0.14674972  0.01071271  0.032889070
#> [6,]  0.6429009  0.07940612 -0.18443277 -0.068830552
```

<sup>Created on 2022-10-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks a lot

**Comment by erichson** [comment]
@DominiqueMakowski, it should be straight forward to implement a simple predict function. You need to (i) standardize the test data using the same parameters (column means / variances) that were used for standardizing the train data; (ii) compute the scores as sparse linear combinations of the columns of the test data.

Say your test data are `Xtest`. Then standardize data as

```
  if(center == TRUE) {
    Xtest <- sweep(Xtest, MARGIN = 2, STATS = spcaObj$center, FUN = "-", check.margin = TRUE)
  }

  if(scale == TRUE) {
    Xtest <- sweep(Xtest, MARGIN = 2, STATS = spcaObj$scale, FUN = "/", check.margin = TRUE)
  }
```

Next compute scores as

`test_scores <- Xtest %*%  spcaObj$loadings`

**Comment by DominiqueMakowski** [comment]
Thanks for your answer! Unfortunately I don't seem to be able to make it work: it seems the dimensions do not match

``` r
spcaObj <- sparsepca::spca(iris[1:50, 1:4], verbose = FALSE)

newdata <- iris[names(spcaObj$center)]
newdata <- sweep(newdata, MARGIN = 2, STATS = spcaObj$center, FUN = "-", check.margin = TRUE)
newdata <- sweep(newdata, MARGIN = 2, STATS = spcaObj$scale, FUN = "/", check.margin = TRUE)


scores <- newdata %*% spcaObj$loadings
#> Error in newdata %*% spcaObj$loadings: requires numeric/complex matrix/vector arguments
```

<sup>Created on 2022-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by erichson** [comment]
Ah, that cannot work. First, spca doesn't scale the variables by default. So first run:

`spcaObj <- sparsepca::spca(iris[1:50, 1:4], center=TRUE, scale=TRUE, verbose = FALSE)`

Then, 

```
newdata <- iris[51:150, 1:4]
newdata <- sweep(newdata, MARGIN = 2, STATS = spcaObj$center, FUN = "-", check.margin = TRUE)
newdata <- sweep(newdata, MARGIN = 2, STATS = spcaObj$scale, FUN = "/", check.margin = TRUE)
```

Now, you need to be careful with the difference between data frames and matrices in R. You can't multply two data frames (?!). So do the following

`scores <- as.matrix(newdata) %*% as.matrix(spcaObj$loadings)`

Maybe there is a better way, but I haven't used R in years. :)

**Comment by DominiqueMakowski** [comment]
It works, thanks!!
